### ISSUE TITLE
add badge with a link to the documentation to the README

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-dataverse#100]
I will provide link and badge shortly, then it can be added to the README

**Comment by adswa** [comment]
The docs are available at http://docs.datalad.org/projects/datalad-dataverse/en/latest/, and the badge that needs to be added to the README is 
[![Documentation Status](https://readthedocs.org/projects/datalad-dataverse/badge/?version=latest)](http://docs.datalad.org/projects/datalad-dataverse/en/latest/?badge=latest)
      
(i.e., put the following at the top of the readme)      
```
[![Documentation Status](https://readthedocs.org/projects/datalad-dataverse/badge/?version=latest)](http://docs.datalad.org/projects/datalad-dataverse/en/latest/?badge=latest)
```

**Comment by mih** [comment]
Fixed by https://github.com/datalad/datalad-dataverse/commit/8a832779f87f35c0b44d106d4b226f398a0e5f16 thanks @enicolaisen 

Closing
