### ISSUE TITLE
Figure how to provide a "docker export"

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-dataverse#11]
Current approach on providing a dataverse-docker relies on `docker-compose` pulling the respective images over network.
For the hackathon, it may not be feasible for everybody to pull several GB over the site's Wifi.

There should be away to have the setup "exported" to an HD or Stick.

We need to figure how to do that (and how to use that as an alternative starting point, obviously)

**Comment by adswa** [comment]
For what its worth, f we fail to do that, demo.dataverse.org can provide an alternative playground - with less configuration-ability, but nevertheless some

**Comment by bpoldrack** [comment]
I guess, since we failed to achieve that in time, this issue has outlived itself at this point.
