### ISSUE TITLE
Implement test for (export) of identical files under different names

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#111]
This should be a non-issue for a normal (non-export) upload -- deduplication is inherent with the annex-key setup. But #18 suggests that complications could arise from a dataset/verse containing multiple redundant copies of the same file under different names.

We should have a test for that.

**Comment by mih** [comment]
I think I have now seen the problem, and it can actually already manifest itself in the export tests.

![image](https://user-images.githubusercontent.com/136479/177820524-6a8c3544-a03f-40ae-a076-208ac510075b.png)

**Comment by mih** [comment]
#226 seems to indicate that it is not possible to deposit two identical files under different names in the same dataset.

However, doing it manually via the web UI works.

**Comment by bpoldrack** [comment]
I think, this is actually an issue with the special remote tracking and using the fileID.
Second upload finds that the key has an ID and tries to replace instead of adding another file with the same key.
