### ISSUE TITLE
What is Dataverse's idea of metadata?

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-dataverse#12]
To figure what we can do in that regard, we should explore https://guides.dataverse.org/en/latest/admin/metadatacustomization.html before the hackathon and a get an idea of what a metadata deposition from datalad (metalad) dataset could look like.

**Comment by jsheunis** [comment]
***WIP...***

From the user guide of dataverse v5.10.1, the section [Dataset and File Management](https://guides.dataverse.org/en/5.10.1/user/dataset-management.html) gives us some info:

>A dataset contains three levels of metadata:
>
>- **Citation Metadata**: any metadata that would be needed for generating a data citation and other general metadata that could be applied to any dataset;
>
>- **Domain Specific Metadata**: with specific support currently for Social Science, Life Science, Geospatial, and Astronomy datasets; and
>
>- **File-level Metadata**: varies depending on the type of data file - for more details see [File Handling](https://guides.dataverse.org/en/5.10.1/user/dataset-management.html#file-handling) section below).

There is also a very useful layout of the fields and metadata formats used for citation metadata and domain-specific metadata in [this google sheet](https://docs.google.com/spreadsheets/d/13HP-jI_cwLDHBetn9UKTREPJ_F4iHdAvhjmlvmYdSSw/edit#gid=0) as referenced from the [Metadata References](https://guides.dataverse.org/en/5.10.1/user/appendix.html#metadata-references) appendix. 

This [Crosswalk document](https://docs.google.com/spreadsheets/d/10Luzti7svVTVKTA-px27oq3RxCUM-QbiTkm8iMd5C54/edit#gid=587531992) contains mappings from Dataverse Metadata v4+ to their supported formats for metadata import and export, including:
- DDI Codebook 2.5
- DataCite 4
- OpenAIRE
- DC Element
- DC Terms
- Schema.org

The crosswalk doc specifies fields and mappings not only for **citation metadata** and **domain-specific metadata**, but also for **system generated metadata** and **terms of use + access metadata**. It is not immediately clear whether the latter two form part (structurally) of the **citation metadata** or some other as yet unspecified metadata type.

**to be continued...**

**Comment by mih** [comment]
I believe we can close this conceptual issue at this point.
