### ISSUE TITLE
Should special remote consider dataset locks?

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-dataverse#149]
I haven't played with it yet, but dataverse provides dataset locks.
See https://guides.dataverse.org/en/latest/api/native-api.html#id74

Not so much about setting a lock, since this seems to require super user permissions and will hence be rarely work out at all,
but requesting them in order to fail graciously when something is locked rather than crash may be necessary.

**Comment by bpoldrack** [comment]
I haven't tried, yet, @adswa. But we don't account for it at all, so it's probably just the HTTPError wich isn't very nice.

**Comment by mih** [comment]
With my current understanding, we already have to report failures for all kinds of reasons. If we do not do that, it needs fixing. If we would "support" dataset locks specifically, we would need to classify what operations are subject to locking, and which not. This seems to have little added value over simply reporting why something is not happening.
