### ISSUE TITLE
Action items from Juelich's research data management challenge

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-dataverse#15]
One of the main causes for this project was commitment to an internal "Research data management challenge" of the Research Center Juelich, in which we aim to provide integration between the imaging core facility data acquisition site and the dataverse instance of the Jülich central library "Jülich Data" ([data.fz-juelich.de](https://data.fz-juelich.de/)). 
Therefore, the workpackages in the proposal are a source of project aims for this hackathon. Here are excerpts from the introduction and workpackage 3 that are relevant, with added emphasis by me:

> "and INM data output will become more findable, accessible, interoperable, and reusable (FAIR) via standardization and **integration with Jülich DATA**"
> WP3: [...] We will partner with the FZJ Central Library to **develop a metadata schema** and workflow to enable INM-ICF users to **programmatically register a dataset with the Jülich Data porta**l. [...] Based on previous work on the interoperability of this solution with key services, such as the OpenScience Framework (http://docs.datalad.org/projects/osf), we will provide INM-ICF users with software that can **create and populate a dataset record on Jülich Data.** [...] As a use case for demonstrating the to-be-developed metadata schema and workflow applied to a heterogeneous dataset, we will register the Jülich **Dual-Tasking & Aging study**, comprising a host of different types of MRI, behavioral and self-report data, with the Jülich DATA portal. Within this project metadata reporting will be restricted to anonymous information, such as acquisition parameters, QC metrics, general study descriptions.

I extract the following out of it:

**Software features**
- [ ] Create a dataverse dataset inside of a dataverse collection (see #14 for a delineation of the terms)
- [ ] Perform a dataset export to the dataverse dataset via their supported upload protocols. There are several supported protocols, but not all of them might be enabled for a given dataverse installation.

**Metadata**
- [ ] Check the metadata schemas in dataverse. There are three levels of metadata: Citation Metadata (any metadata that would be needed for generating a data citation and other general metadata that could be applied to any dataset); Domain Specific Metadata (with specific support currently for Social Science, Life Science, Geospatial, and Astronomy datasets); and File-level Metadata (varies depending on the type of data file)
- [ ] Check for feasibility of metadata extractors for the available schemas

**Usecase/Examples**
- [ ] Take a look at the DTA dataset and check how easy the required anonymous information can be extracted
- [ ] Figure out how this metadata can best be mapped to available dataverse metadata standards
- [ ] Find out which version of dataverse is run at the central library, and what the supported features are (who can create what, which data upload protocols are enabled, ...). 
- [ ] Make a list of features the Jülich dataverse has or hasn't, check that concepts in #14 apply to it

**Comment by adswa** [comment]
Thanks for raising this. I do feel like my personal interests in the hackathon also do not completely align with the RDM challenge proposal, so I personally feel that the RDM challenge goals are only a subset of the hackathons action items (but having them in mind and making our lives easier when that one is due is attractive). 
I don't have a really helpful answer but there are two things I want to note:
- my approach to the issues is still a bit unstructured, I read into the proposal first and tried to capture its contents here before engaging with the broader scope of our hackathon project - I don't want to make the impression that the RDM challenge is the sole driver of action items, just one of many
. When I split the tasks into the 3 areas I did this with the intent to create orthogonal, more or less stand-alone action items that could be worked on separately in case we had people interested in it. I think your comment gave me a new perspective on it, and I agree that some internal prioritization of these tasks could indeed help to make the hackathon project more manageable. As for what the prios are .... phew, tough question :/ I think this priorization is best be made bottom up based on interests/skills of the people hacking (e.g., non-metadata people working on metadata only sounds ineffective). Any thoughts on that are most welcome!

**Comment by jsheunis** [comment]
> my approach to the issues is still a bit unstructured, I read into the proposal first and tried to capture its contents here before engaging with the broader scope of our hackathon project - I don't want to make the impression that the RDM challenge is the sole driver of action items, just one of many

Thanks for clarifying 👍 

> When I split the tasks into the 3 areas I did this with the intent to create orthogonal, more or less stand-alone action items that could be worked on separately in case we had people interested in it.

I like this approach. We'll probably learn more as our approach and knowledge become more structured, but I suspect some core functionality like "dataset upload/creation" will in any case have to precede steps like "metadata addition", which gives at least a short-term indication of priority.
