### ISSUE TITLE
Address transfer of large data

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-dataverse#155]
There was a concern about the download method implemented by the special remote being memory constraint. This is true. The same is true for upload as implemented by pyDataverse. Both are "naive" and should be improved to deal with large files. They are both expecting the entire content of a file to be put into a single request/response.

**Comment by mih** [comment]
The datalad-next UrlOperations has a slot for uploads too. There is nothing for HTTP implemented yet, but `requests` makes streaming uploads straightforward.

**Comment by mih** [comment]
pydataverse is using this pattern for uploads

https://github.com/gdcc/pyDataverse/blob/master/src/pyDataverse/api.py#L1683-L1686

leading to

https://requests.readthedocs.io/en/latest/user/advanced/?highlight=stream%20upload#streaming-uploads

which should do streaming. So this is fine. I cannot see the same thing being true for a `GET` (download).

**Comment by bpoldrack** [comment]
Yeah, not sure what led me to think that pydataverse does the same on upload as our hackathon implementation of download. Should have included a pointer to what I was looking at.

**Comment by mih** [comment]
Closing as invalid.
