### ISSUE TITLE
Dataset metadata deposition

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-dataverse#156]
We need a way to deposit a dataset w/o actual data content, but including (some) dataset level metadata.

The repository part would probably still be uploaded, so it's clonable, but the crucial part here is the metadata.
Currently, there's only rudimentary, standard dataverse "metadata" like title, author, etc via switches for `create-sibling-dataverse`. This is neither nice nor particularly useful.

Idea so far was to come up with a datalad specific metadata block definition for dataverse and have it deployed by whoever has the appropriate role.
The default metadata blocks by dataverse are domain specific and don't cover what we automatically know about the dataset and its provenance, identity, etc. However, eventually there could be fitting extractors for them. So, we should keep that in mind, I think and have a mechanism that allows to choose the target and the extractor or something along those lines.

Tasks:

- Come up with such a definition that could be filled from metalad via the datalad core extractor. 
- decide how to pass this to `create-sibling-dataverse` (or even `push` - which connects to the question of how to update the metadata). Possibly a dataset config, that can be picked up by either a `push` patch or the special remote itself, when it pushes the "special keys" `XDLR-...`. ( @christian-monch : Guess, we should address those two points together)
- Find out how to deploy the definition (we'll need you here, I suppose, @loj )

**Comment by mih** [comment]
I have now been able to spend considerable time looking at the current implementation and the plan that is sketched here. I will close this issue, and successively replace it with issue for a different approach. The primary reason for that is that the sketched plan cannot be implemented until fundamental questions are answered at a fairly global scale (what is relevant metadata, how can metalad provide it, how custom metadata blocks can be deployed). Taken together this renders this approach fairly inactionable.

Instead I will push for:

- let `create-sibling-dataverse` deal with creating a dataverse dataset, and just that -- although the outcome of that is labeled  "neither nice nor particularly useful" above I disagree and believe that it would be good enough for most people
- let users define and provide metadata directly, without installing `metalad` as a requirement. The current state of `metalad` positions it at the plumbing level tooling. Here it would be perfectly sufficient for most users to provide a few key-value pairs, for which their would know what they are. Easy to implement, easy to document.
- keep metadata updates away from `create-sibling-dataverse`. It has never led to something useful to overload these commands with everything one can think of. Hardly ever does a user know exactly what they want at the time of creation. Instead, we should provided something like `dataverse-update-metadata` to perform metadata updates at any moment, without the implementation or the user having to worry about creating anything.
