### ISSUE TITLE
Documenting experience with Dataverse v4 issues

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-dataverse#18]
In case this could prove useful, I am writing down a few notes from my previous experience with creating a collection + dataset using an installation of Dataverse 4 in 2020/2021, on [dataverse.nl](https://dataverse.nl/). This is the dataset in question: https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/R1TNL8

### Issue 1

One main issue that I encountered was with uploading the full BIDS dataset via the web portal's [HTTP upload interface](https://guides.dataverse.org/en/5.10.1/user/dataset-management.html#http-upload). I had received a vague error message like "This file already exists" with no reference to the duplicate files. I had to inspect this manually in the file list (and also via API). I found the files in question to be missing, and when trying to upload them again, received the same issue. This was then found to be a known issue in dataverse. Here's just a quick selection of closed issues that highlight the progression of these challenges:
- https://github.com/IQSS/dataverse/issues/1165
- https://github.com/IQSS/dataverse/issues/2467
- https://github.com/IQSS/dataverse/issues/2621
- https://github.com/IQSS/dataverse/issues/2955
- https://github.com/IQSS/dataverse/issues/3571
- https://github.com/IQSS/dataverse/issues/4813
- https://github.com/IQSS/dataverse/issues/6574
- https://github.com/IQSS/dataverse/issues/7223

The workaround at that point was to upload the files in compressed format. I don't know why this worked, but it did (after many tries).

### Issue 2

The compressed files upload approach also "solved" the other issue that I had, which was that the HTTP uploader couldn't handle more than ~1000 files at a time. However, to be sure that I could make use of the tree view of files in the dataset, I had to compress my subset of files into the same directory structure that it would exist in in the final tree. I didn't have to explicitly specify the relative path of a file with extra metadata. I suspect once dataverse processed the compressed file after upload, there was some internal mapping to the path field in file-specific metadata.

Here is a link to information on the dataverse user docs regarding compressed files: https://guides.dataverse.org/en/5.10.1/user/dataset-management.html#compressed-files

### Issue 3

Another issue was bulk download of the whole dataset from the webportal, which resulted in a `414 Request-URI Too Long ` error. Here's a related issue:
- https://github.com/IQSS/dataverse/issues/6943

The suggestion then was to wait for the upgrade to dataverse v5 to address this issue. I waited for a long time, but perhaps they have (hopefully) already addressed this issue and completed the upgrade.

### Issue 4

Lastly, I also encountered an issue with the guestbook functionality. It was possible to circumvent the guestbook functionality via the API, which is meant to get people to agree to some data use terms digitally before download. I had to restrict all files in the dataset as a workaround for this issue, and this required manual access granting whenever someone requests a download. This is of course the opposite of what wants to achieve with the guestbook functionality. The guestbook functionality and issue are described here:
- https://github.com/datalad/datalad-dataverse/issues/8

**Comment by mih** [comment]
Thanks for writing this up. Our implementation so far has avoided non-API access successfully. I am hoping that we do not run into any of these issues. I filed #111 as the most likely problem we could face -- which we should specifically test for.

Re dataverse v4: I think we should make explicit that we do not do not aim to support version prior v5 #112

With these more specific issues filed, I am closing this background info issue.
