### ISSUE TITLE
Current metadata validation must not be unconditional

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-dataverse#193]
Currently, `create-sibling-dataverse` unconditionally uses the validation provided by pyDataverse on the JSON record passed to the command. In this shape that only works for dataverse default settings. A concrete instance (and collection!) may define additional metadata blocks (as does JülichDATA) and different required fields. The current unconditional validation would fail on a correct record, making it impossible to use `create-sibling-dataverse` correctly in such a case.

I'll write down a more in-depth exploration of that topic and link here. But want to leave the info here, that in order to properly explore and debug, the 

```
    if not dv_dataset.validate_json():
        raise InvalidDatasetMetadata
```

in `_create_dv_dataset` needs to go (or become optional) for now.

**Comment by mih** [comment]
With #224 `add_sibling_dataverse` no handles metadata.
