### ISSUE TITLE
Less visually intrusive encoding of ".datalad"-dirs in dataverse datasets

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-dataverse#218]
The current file name-mangling quotes all appearances of ``'.'`` as ``'_2E'`` in order to get around the problem that dataverse silently ignores all leading ``'.'`` in directory names. I.e. for dataverse datasets the directory names ``'.datalad'``, ``'..datalad'`` and ``'datalad'`` are identical.

The current quoting leads to the presence of ``'_2Edatalad'`` directories in the dataverse datasets. That is visually disturbing. Instead the leading dots should be encoded as ``'_.'`` (and leading `_` have then to be encoded as `__` in order to prevent collisions between ``.x``  and ``_.x``). With this encoding the ``.datalad``-directory would appear under the name ``_.datalad`` in dataverse-datasets

**Comment by mih** [comment]
Done with #227. Now looks like this

![image](https://user-images.githubusercontent.com/136479/224698401-a97aa878-1b53-40a2-a474-869df4aa625a.png)
