### ISSUE TITLE
Replace `create_sibling_dataverse()` with `add_sibling_dataverse()`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#224]
The `create_sibling_dataverse` command is not in a good place. Some key issues are

- https://github.com/datalad/datalad-dataverse/issues/136
- https://github.com/datalad/datalad-dataverse/issues/139
- https://github.com/datalad/datalad-dataverse/issues/152

However, the biggest unresolved issue is metadata declaration for a dataset. Given that there is no readily implementable concept yet, and any `create` needs to be followed up with manual editing on the web UI, there is little point in having such a command.

The opportune alternative seems to be an `add-sibling-dataverse` command, that does the "same", but expects an existing dataverse dataset as a target to be specified.

This should not cause more manual labor (maybe even less for now), and makes sure that datasets are created according to the policies of a particular dataverse instance. This would remove the following issues from the "problem surface":

- https://github.com/datalad/datalad-dataverse/issues/193
- https://github.com/datalad/datalad-dataverse/issues/152
- https://github.com/datalad/datalad-dataverse/issues/139
- https://github.com/datalad/datalad-dataverse/issues/137
- https://github.com/datalad/datalad-dataverse/issues/186
- https://github.com/datalad/datalad-dataverse/issues/192
- https://github.com/datalad/datalad-dataverse/issues/136
- https://github.com/datalad/datalad-dataverse/issues/102

With this change in paradigm, the recursive-mode feature of `create_sibling_dataverse` has to be critically evaluated. It is a thing wrapper around `for-each-dataset`, and, as such, offers litte extra convenience. At the same time it prescribes a tight corset of dataset representation on dataverse.

I believe it should be removed.

As a replacement, `add_sibling_dataverse` should support a `prefix` option (`None` by default) that enables users to identify a root `directoryLabel` for a particular DataLad dataset inside a Dataverse dataset. This makes it possible to represent any number of DataLad datasets in a single Dataverse dataset. This matches the need to create the Dataverse dataset manually (would be a one-time effort), and does not constrain automation of data deposition with large DataLad dataset hierarchies. Providing `prefix` rather than `--recursive` enables users to choose their own organization of subdatasets within the Dataverse dataset, rather than imposing a select few. Recursive operation can be done conveniently via `for_each_dataset`.

**Comment by mih** [comment]
Reopening as #238 was merged for technical reasons only.

**Comment by adswa** [comment]
The linked issues are all resolved, but this isn't implemented yet:

> As a replacement, add_sibling_dataverse should support a prefix option (None by default) that enables users to identify a root directoryLabel for a particular DataLad dataset inside a Dataverse dataset. This makes it possible to represent any number of DataLad datasets in a single Dataverse dataset. This matches the need to create the Dataverse dataset manually (would be a one-time effort), and does not constrain automation of data deposition with large DataLad dataset hierarchies. Providing prefix rather than --recursive enables users to choose their own organization of subdatasets within the Dataverse dataset, rather than imposing a select few. Recursive operation can be done conveniently via for_each_dataset.

**Comment by mih** [comment]
I have filed #271 for this now. We can close here.
