### ISSUE TITLE
Investigate `__docformat__ = "numpy"`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#228]
#227 introduces it in a single file.

**Comment by mih** [comment]
It seems not critical to set this and `numpy` is a compatible flavor of `restructuredtext`.

It would make sense to make this uniform and replace it in all files with either one. Leaning towards `numpy`.

Any opinions?

**Comment by adswa** [comment]
[This PEP](https://peps.python.org/pep-0287/) recommends restructuredtext explicitly

**Comment by mih** [comment]
Oh! Good catch! But `numpy` is a flavor of restructured text and maybe the latter wasn't known in 2002?

**Comment by mslw** [comment]
AFAIK our Sphinx configuration for building docs has the [napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) extension enabled, which takes care of converting Numpy (or Google) style docstrings into reStructuredText for Sphinx to build the documentation website. And I tend to agree with napoleon's documentation in that "reStructuredText is great, but it creates visually dense, hard to read docstrings".

I could not verify though, whether Sphinx / Napoleon actually take the `__docformat__` variable into account.

**Comment by mih** [comment]
I looked into this a bit more. Conclusions:

- we do not seem need *any* `__docformat__` declarations. Neither napoleon (we use), nor numpydoc (we do not use) require it.
- it can aid some apidoc generators, but it seems that most support declaration via global parameter, or use a napoleon fork, or do not support numpy as a flavor

So this has more or less annecdotal value, and is certainly no worse than a `restructuredtext` declaration.
