### ISSUE TITLE
Add a glossary of dataverse and DataLad terminology into the docs

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-dataverse#25]
I think it would be very valuable to define common Dataverse terms (as started in #14) and DataLad terms (could be taken from [the handbook's glossary](http://handbook.datalad.org/en/latest/glossary.html) and how they relate in a stand-alone section in the docs.

**Comment by adswa** [comment]
@loj could you maybe push your work so far? :)

**Comment by loj** [comment]
Yes, sorry about that! I've pushed the very start of a glossary in #81

**Comment by mih** [comment]
With http://docs.datalad.org/projects/datalad-dataverse/en/latest/glossary.html being accessible, I think this issue can be closed.
