### ISSUE TITLE
DOC: update docs to reflect recent state of the package

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-dataverse#256]
Main TODOs:

- [x] Remove outdated `Attention` blocks
- [ ] look into https://github.com/datalad/datalad-dataverse/issues/241.
- [x] Update python and cli reference pages
- [x] Add not-supported clauses (ideally each with a short description of why/what/how/alternatives):
   - no unicode support
   - no supported for released dataverse datasets
   - no support for dataverse prior 5.13
 
Anything else?

**Comment by mih** [comment]
Thx much. I think we can close this
