### ISSUE TITLE
Programmatically determine list of dataset "subjects"

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#27]
Calling `pyDataverse.api.NativeApi.create_dataset()` requires to specified "subjects". This is not optional, and it cannot be an arbitrary string.

The WebUI exposes a predefined list of identifiers

![image](https://user-images.githubusercontent.com/136479/173370067-3c8cf253-4865-4494-a764-7f88c1ee7b43.png)

we have to be able to query this list programmatically, in order to be able to give meaningful advice for composing this mandatory dataset metadata.

**Comment by mih** [comment]
I confirmed that this list is not defined in `pyDataverse` code.

**Comment by ksarink** [comment]
> This seems to be the request to get that list:
> 
> ```
> ❱ curl -H X-Dataverse-key:$API_TOKEN $SERVER_URL/api/metadatablocks 
> {"status":"OK","data":[{"id":1,"displayName":"Citation Metadata","name":"citation"},{"id":2,"displayName":"Geospatial Metadata","name":"geospatial"},{"id":3,"displayName":"Social Science and Humanities Metadata","name":"socialscience"},{"id":4,"displayName":"Astronomy and Astrophysics Metadata","name":"astrophysics"},{"id":5,"displayName":"Life Sciences Metadata","name":"biomedical"},{"id":6,"displayName":"Journal Metadata","name":"journal"}]} 
> ```

This api endpoint does not seem to provide the information needed. Under $SERVER_URL/api/metadatablocks/citation/ the field subject is defined but there is no information about the possible values. See:
```
"subject": {
    "name": "subject",
    "displayName": "Subject",
    "title": "Subject",
    "type": "TEXT",
    "watermark": "",
    "description": "Domain-specific Subject Categories that are topically relevant to the Dataset."
},
```

**Comment by bpoldrack** [comment]
Here is the list as extracted from the webinterface:

```
['Agricultural Sciences',
 'Arts and Humanities',
 'Astronomy and Astrophysics',
 'Business and Management',
 'Chemistry',
 'Computer and Information Science',
 'Earth and Environmental Sciences',
 'Engineering',
 'Law',
 'Mathematical Sciences',
 'Medicine, Health and Life Sciences',
 'Physics',
 'Social Sciences',
 'Other']
 ```

**Comment by bpoldrack** [comment]
FTR: Should have looked at the linked commit in the dataverse issue first.

From within the docker I can get it here: 

`curl http://localhost:8080/api/admin/datasetfield/controlledVocabulary/subject`

Just noting it here, in case that endpoint becomes relevant for us in the future.

**Comment by pdurbin** [comment]
Please note that the plan is to introduce a non-admin API (to show the list of subjects, etc.) in this PR:

- https://github.com/IQSS/dataverse/pull/9213
