### ISSUE TITLE
Determine Dataverse API equivalents for git-annex special remote operations

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#28]
We need to explore what types of operations can be mapped onto the dataverse API in order to see what functionality can be supported at this most basic level. It would be very attractive to use this layer, because it would automatically enable interoperability with dataverse for file deposition, file retrieval, Git history deposition, datalad-clone from dataverse DOIs, and even usage outside datalad with git-annex directly.

Note that git-annex operates strictly in a per-file-version mode, so things like bulk-uploads of ZIP file etc. are not part of the possibilities.

Here is the list of operations:

### Must have

- `TRANSFER STORE`: file upload to deposit under a name matching the annex key (git-annex content identifier)
- `TRANSFER RETRIEVE` file download based on an annex key
- `CHECKPRESENT`: report whether file matching a particular annex key is available. It is imported that the implementation does not report presence, when in-fact an upload is still ongoing and not complete.
- `REMOVE`: Delete a file matching a particular annex key

### Nice to have

- `SETURLPRESENT` determine a (persistent) URL where file content can be downloaded for a file deposited by `TRANSFER STORE`
- `TRANSFEREXPORT STORE`: Like `TRANSFER STORE` but store a file under a specific filename on dataverse
- `TRANSFEREXPORT RETRIEVE`: Like `TRANSFER RETRIEVE`, but retrieve file content by a file name given to `TRANSFEREXPORT STORE` rather than an annex key
- `CHECKPRESENTEXPORT`: Like `CHECKPRESENT`, but check for a filename given to `TRANSFEREXPORT STORE`
- `REMOVEEXPORT`: Like `REMOVE`, but remove a file by filename given to `TRANSFEREXPORT STORE`

### To make things more efficient/convenient

- `REMOVEEXPORTDIRECTORY`: remove all files with "logical" paths (as given to `TRANSFEREXPORT STORE`) inside a particular directory
- `RENAMEEXPORT`: Change the "logical" path of a deposited file

### Extremely nice to have

Ability to report a list of files in a dataset with the following information for each file

- filename (logical/tree path)
- size in bytes
- content identifier: and identifier provided by (or computable from information provided by) dataverse that is
  - stable, so when a file has not changed, its content identifier remains the same
  - changes when a file is modified
  - be as unique as possible, but not necessarily fully unique. A hash of the content would be ideal, but a (size, mtime, inode) tuple is better than nothing
  - be reasonably short (needs to be tracked)

and possibly the same even for historical version.

**Comment by bpoldrack** [comment]
> Note that git-annex operates strictly in a per-file-version mode, so things like bulk-uploads of ZIP file etc. are not part of the possibilities.

Just leaving a reminder, that we have `datalad-archives`. For some usecases that detour may be a fit. Nothing to implement here, but we could document how to make use of that in combination with dataverse, since the archive approach seems relatively common with dataverse.

**Comment by bpoldrack** [comment]
> REMOVE: Delete a file matching a particular annex key

According to dataverse matrix channel, deletion is only possible via SWORD.

This is from the [respective docs](https://guides.dataverse.org/en/5.10.1/api/sword.html#delete-a-file-by-database-id):

`curl -u $API_TOKEN: -X DELETE https://$HOSTNAME/dvn/api/data-deposit/v1.1/swordv2/edit-media/file/123`

However, that should be relatively convenient, via `pydataverse.api.API.delete_request`.

**Comment by bpoldrack** [comment]
Generally, the main issue seems to know the annex key of a file on dataverse (assuming we want a proper file tree there, not an annex object tree).
I have not found a way to attach arbitrary metadata fields to a file yet. However, files in a dataverse dataset do have an ID and possibly a persistent identifier (given by the dataverse instance). We could map them to their annex keys. I see two ways ATM:

- have the special remote commit (and maintain) the mapping in the repository (could be a file in `.datalad` and/or configurable in the special remote config)
- add a "special file" containing the mapping to the dataverse dataset (but not the datalad dataset). It may useful in this case to have closer look at dataverse's support for tabular data files

**Comment by bpoldrack** [comment]
`CHECKPRESENT`:  `api.NativeApi.get_datafiles_metadata(dataset_pid).json()`

`TRANSFER-STORE`: `df = pyDataverse.models.Datafile(); df.set({"pid": dataset_pid, "filename": df_filename}); api.NativeApi.upload_datafile(ds_pid, df_filename, df.json())`  # TODO: set file path

**Comment by bpoldrack** [comment]
`TRANSFER-RETRIEVE`: `pyDataverse.api.DataAccessApi.get_datafile(file_id)` (See https://pydataverse.readthedocs.io/en/latest/user/basic-usage.html#download-and-save-a-dataset-to-disk)

**Comment by bpoldrack** [comment]
I think in terms of what to use, `export` or not doesn't make a difference for the `TRANSFER*` implementations. We have the file path in the metadata that we query for.

**Comment by bpoldrack** [comment]
`SETURLPRESENT`: I think, the URL of an uploaded file is `BASE_URL/api/access/datafile/ID` (as in: works for me).

**Comment by jernsting** [comment]
> According to dataverse matrix channel, deletion is only possible via SWORD. This is from the [respective docs](https://guides.dataverse.org/en/5.10.1/api/sword.html#delete-a-file-by-database-id):
curl -u $API_TOKEN: -X DELETE https://$HOSTNAME/dvn/api/data-deposit/v1.1/swordv2/edit-media/file/123
However, that should be relatively convenient, via pydataverse.api.API.delete_request (there are functions for all HTTP request methods, that integrate authentication).

pydataverse.api.API.delete_request does not work as it does not provide acces to the BasicAuth feature which is needed for the SWORD-API. Bare requests work.

**Comment by jernsting** [comment]
"Must Have"-functions are now present (see pull requests). Cleanup and removal of duplicated code is left todo.

**Comment by jernsting** [comment]
> TRANSFEREXPORT STORE: Like TRANSFER STORE but store a file under a specific filename on dataverse
> TRANSFEREXPORT RETRIEVE: Like TRANSFER RETRIEVE, but retrieve file content by a file name given to TRANSFEREXPORT STORE rather than an annex key
> CHECKPRESENTEXPORT: Like CHECKPRESENT, but check for a filename given to TRANSFEREXPORT STORE
> REMOVEEXPORT: Like REMOVE, but remove a file by filename given to TRANSFEREXPORT STORE

These functions are now implemented (#85). Dataverse removes leading dot chars (see #83), but the exporttree works as expected.

**Comment by mih** [comment]
I think we can close this conceptual issue now. Much thanks to everyone who actually already implemented this mapping!
