### ISSUE TITLE
Declare software dependencies

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#29]
This extension will require token handling. It makes little sense to me (@mih) to fiddle with the implementation in datalad-core. Instead we should use the latest features in datalad-next (which brings `datalad_next >= 0.2.0`, latest is `0.3.0`).

For the implementation of tests, it makes sense to me (@mih) to use `pytest` right from the start. However, a datalad version (`0.17.0` with the necessary utilities) has not been released yet. This implies an additional dependency on datalad-core's `master` branch --beyond the dependency link via `datalad-next`.

Additional dependencies will possibly come via #7.

**Comment by adswa** [comment]
I agree that the credential handling from datalad-next is best suited
