### ISSUE TITLE
Tests (against demo.dataverse.org) are broken

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#291]
Pretty much anything yields

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://demo.dataverse.org/api/v1/dataverses/dv-5a8ce96e-d51a-11ed-a827-701ab88b716c/datasets?User-Agent=pydataverse&key=...
```

This replicates locally for me.

**Comment by adswa** [comment]
I'm seeing similar things, but I also have trouble reaching demo.dataverse.org reliably - maybe their servers have some unusual load or maintenance or other issues that could also affect our tests.

**Comment by adswa** [comment]
I've retried running the tests, and they sadly remain broken

**Comment by adswa** [comment]
this isn't an issue anymore
