### ISSUE TITLE
Link to Documentation leads to 404 -> wrong link

### ISSUE THREAD

**Issue by behinger** [datalad/datalad-dataverse#295]
Hi!
If I click on "docs-passing" in the Readme.md I get the link:
`http://docs.datalad.org/en/stable/projects/datalad-dataverse/en/latest/?badge=latest` which 404s.

The correct link should be

`http://docs.datalad.org/projects/dataverse/en/stable/`

I can do a pull, or you fix it directly :)
Cheers, Benedikt

**Comment by adswa** [comment]
Oh no, we completely missed this in our notifications! Thanks for reporting! And a PR would be most welcome :)
