### ISSUE TITLE
add-sibling-dataverse fails with `'Response' object has no attribute 'ok'`

### ISSUE THREAD

**Issue by shoeffner** [datalad/datalad-dataverse#308]
When adding a dataverse sibling, the current main branch fails with `'Response' object has no attribute 'ok'`:
```bash
$ datalad add-sibling-dataverse --credential demodataverse -s dataverse http://localhost:8080 doi:10.5072/FK2/S1OTS1
CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false annex initremote dataverse-storage type=external externaltype=dataverse url=http://localhost:8080 doi=doi:10.5072/FK2/S1OTS1 exporttree=no encryption=none credential=demodataverse -c annex.dotfiles=true' failed with exitcode 1 under /Users/shoeffner/Projects/private/local-git
initremote dataverse-storage 
failed
git-annex: external special remote error: 'Response' object has no attribute 'ok'
initremote: 1 failed
```

This is likely because (I am doing guesswork, haven't checked the code thoroughly) [requests' Response object has an attribute ok](https://requests.readthedocs.io/en/latest/api/#requests.Response.ok), but httpx' doesn't. I assume at some point the code in pydataverse was refactored to use httpx instead of requests and thus broke the API (and since datalad-dataverse does not pin the version I got the latest with httpx).

**Comment by mih** [comment]
Thank you! I see that too.

I enabled weekly CI runs now that would catch something like this quicker. The change must have happened within the last 9 months. I am running `datalad_dataverse-1.0.1` with `pydataverse-0.3.3`
