### ISSUE TITLE
Create a scaffold for the special remote

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-dataverse#31]
One of the cornerstones of the project is a special remote implementation that can talk to dataverse. This will need to be implemented based on a scaffold. Some not exactly perfect examples are in datalad core in https://github.com/datalad/datalad/tree/master/datalad/customremotes, and like them, we will use https://github.com/Lykos153/AnnexRemote as a basis.

**Comment by mih** [comment]
Fixed by #34
