### ISSUE TITLE
Credit contributions with the allcontributors-bot

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-dataverse#44]
#22 is done, and the bot is installed and works (#41). Now we need to add contributors! Please add contributions generously for all contributions you see. The emoji key that lists the possible contribution types is https://allcontributors.org/docs/en/emoji-key and the call looks like this:

``hey @all-contributors please add [contributor] for [contrib1, contrib2, contrib3]``

**Comment by adswa** [comment]
hey @all-contributors please add @nadinespy for infra

**Comment by nadinespy** [comment]
hey @all-contributors please add @bpoldrack for infra, code, doc, maintenance, review, ideas, tool

**Comment by nadinespy** [comment]
hey @all-contributors please add @adswa for code, ideas, infra, doc, maintenance, review, tool

**Comment by nadinespy** [comment]
hey @all-contributors please add @mih for code, ideas, maintenance, infra, review, tool

**Comment by adswa** [comment]
I think you need to merge the pull requests to prevent merge conflicts, @nadinespy

**Comment by nadinespy** [comment]
hey @all-contributors please add@jernsting for code

**Comment by adswa** [comment]
I think your call is completely correct @nadinespy , the bot is just a bit deaf sometimes...

**Comment by nadinespy** [comment]
hey @all-contributors please add @jernsting for code

**Comment by nadinespy** [comment]
hey @all-contributors please add @ksarink for code

**Comment by nadinespy** [comment]
hey @all-contributors please add @rgbayrak for doc

**Comment by nadinespy** [comment]
hey @all-contributors please add @enicolaisen for doc

**Comment by nadinespy** [comment]
hey @all-contributors please add @effigies for code

**Comment by nadinespy** [comment]
hey @all-contributors please add @aqw for infra, code, maintenance, tool

**Comment by nadinespy** [comment]
hey @all-contributors please add @Shammi270787 for code

**Comment by adswa** [comment]
hey @all-contributors please add @jadecci for code, review, userTesting

**Comment by adswa** [comment]
hey @all-contributors please add @loj for doc, research

**Comment by adswa** [comment]
hey https://github.com/all-contributors please add @loj for research

**Comment by adswa** [comment]
the bot doesn't seem to like this contribution type -.-

**Comment by adswa** [comment]
We caught at least a majority of contributors, and can continue more easily now in PRs or issues. This issue has served its purpose

**Comment by nadinespy** [comment]
hey @all-contributors please add @nadinespy for doc
