### ISSUE TITLE
Docker hub is unhappy with our test frequency

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#47]
```
ERROR: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Build exited with code 1
```

We should limit the runs (maybe disable the branch CI run and just keep the PR one). Or follow the advice.

**Comment by adswa** [comment]
I will look into this

**Comment by adswa** [comment]
Here is what the docs say:

> Docker Hub limits the number of Docker image downloads (“pulls”) based on the account type of the user pulling the image. Pull rates limits are based on individual IP address. For anonymous users, the rate limit is set to 100 pulls per 6 hours per IP address. For [authenticated](https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests) users, it is 200 pulls per 6 hour period. There are no limits for users with a paid Docker subscription.

I.e., if we use authentication we can double the amount of pulls we can do. I will set up an account and see how easy it is to add login to the CIs.

**Comment by adswa** [comment]
Let's see if 200 pulls per 6 hours are enough. Alternatively, we should try to add the containers to GitHubs container registry (https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) and pull from there (seems to be free and not rate limited as far as I can tell).
