### ISSUE TITLE
Import data to dataverse

### ISSUE THREAD

**Issue by Niousha-Dehestani** [datalad/datalad-dataverse#49]
I used this script to import data to dataverse: 

 export API_TOKEN= **********

export SERVER_URL=https://demo.dataverse.org

export DATAVERSE_ID=root

export PERSISTENT_IDENTIFIER=doi.org/******

curl -H X-Dataverse-key:$API_TOKEN -X POST $SERVER_URL/api/dataverses/$DATAVERSE_ID/datasets/:import?pid=$PERSISTENT_IDENTIFIER&release=yes --upload-file dataset.json

**Comment by bpoldrack** [comment]
Just for the record: If I got that right, then dataverse instances can be set up to provide/generate a DOI / "persistent identifier" from their end. hence, I am not sure to what extend it would generalize to provide one from the user's end.
Anyone experience with that (on real world instances, I mean)?

**Comment by mih** [comment]
We are now able to upload via datalad. Thx!
