### ISSUE TITLE
Check existing python modules for API access

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-dataverse#7]
There are at least two:

https://github.com/gdcc/pyDataverse
https://github.com/IQSS/dataverse-client-python

The former seems a little more fitting for us at a first glance, but that needs a bit of playing with it, I guess.

**Comment by mih** [comment]
I posted to the dataverse matrix channel, if there is any feedback re `pydataverse`

**Comment by bpoldrack** [comment]
I think we've pretty much settled on pydataverse by now. Closing.
