### ISSUE TITLE
Needed: default dataset description

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#86]
Whenever no custom dataset description is available or provided, we still need to provide one to dataverse. The default looks of a dataverse dataset that had a datalad dataset Git repo pushed to it is this:

![image](https://user-images.githubusercontent.com/136479/174425088-44c78912-3092-4ad0-a7af-29b3de96b5ca.png)

It would make sense to anchor the default description for this mode on explaining what a datalad dataset is, and how one would work with it, and what the nature of these two files is (and also the similarly looking, equally cryptic annex keys) -- i.e. say that this is not meant to be consumed without datalad.

We already have something similar in https://github.com/datalad-datasets/human-connectome-project-openaccess, which could be tailored for the present needs.

**Comment by bpoldrack** [comment]
FTR: I think it should also contain the `datalad-annex` URL to use for cloning this dataset.

**Comment by mih** [comment]
With #87 that URL would be the URL of the very same HTML page

**Comment by bpoldrack** [comment]
True. Didn't realize that yet. That's pretty cool.

**Comment by enicolaisen** [comment]
so this task is basically creating a README.md file like the one Michael pointed out right? Am I missing something?

**Comment by mih** [comment]
https://github.com/datalad/datalad-dataverse/blob/f33c68fd3eab0c7dfca9e8c2ab091d9422e0ca52/datalad_dataverse/create_sibling_dataverse.py#L721 yields a default description, so this issue can be closed.
